### ISSUE TITLE
Browser console throws various errors.

### ISSUE THREAD

**Issue by TinFoilFox** [samfry13/clippy#10]
When browsing the site various errors pop up in the console like this:

![image](https://user-images.githubusercontent.com/15332259/190681860-166bba8c-8869-469e-809c-40d66ac2737c.png)

The errors referenced are:
- https://reactjs.org/docs/error-decoder.html/?invariant=425
- https://reactjs.org/docs/error-decoder.html/?invariant=418
- https://reactjs.org/docs/error-decoder.html/?invariant=423

Functionality seems unimpaired and everything seems to work.
Are these errors important or can they be safely ignored?
If they can be ignored can they also be suppressed?

**Comment by samfry13** [comment]
When do these errors happen? It looks like there are a lot of them, do they happen when you're doing something specific?

**Comment by TinFoilFox** [comment]
I don't know, it was happening on several browsers but now it's good. I'll try again later to see if I can reproduce it.

**Comment by samfry13** [comment]
I think I figured it out. It looks like it's an issue with server-side rendering, likely due to the dates on the videos. The server is rendering, and formatting the dates as UTC, and then sending them to the browser where it gets rendered as whatever timezone you're in, which it doesn't like. Solution would likely be to do some hiding shenanigans in the html.

[Source](https://github.com/vercel/next.js/discussions/38263)

**Comment by TinFoilFox** [comment]
Ah I was able to reproduce it. It happened after deleting a video.

or maybe it's the dates like you said.
